### ISSUE TITLE
How to pass in a JSON variable into env_vars

### ISSUE THREAD

**Issue by Doggie52** [google-github-actions/deploy-cloud-functions#39]
### Question

I'm trying to pass in a JSON variable into `env_vars` but ending up with issues parsing the commas, as `parseEnvVars` thinks those are separate environment variables and hence looks for `=` without finding it.

**Comment by bharathkkb** [comment]
Hi @Doggie52
Thanks for the report, this is much asked for usecase. Hoping to allow this with https://github.com/google-github-actions/deploy-cloud-functions/pull/34 which will allow you to pass in a yaml file and then you should be able to
```yaml
foo: '{"bar":"baz"}'
```

**Comment by Doggie52** [comment]
Would that use case allow for passing in a yaml file file with a variable set from a secret?

Basically I have a secret that is a JSON object, and I want to pass this JSON object (as a string) into an env variable for my function.

**Comment by bharathkkb** [comment]
While possible with #34 the general cloud functions best practice is not use env vars for secrets in general. More details here: https://cloud.google.com/functions/docs/env-var#managing_secrets
Closing this issue since we released 0.3.0 which has the env_var_file feature. Feel free to reopen if you run into any issues.

**Comment by Doggie52** [comment]
Thanks for the advice, turns out it was an entirely unnecessary secret to pass anyway. Great new feature though regardless!
